export const boardSizes = {
  desktop: { width: 1680, height: 980 },
  mobile: { width: 900, height: 1360 },
};

const baseUrl = import.meta.env.BASE_URL || "/";

function assetPath(path) {
  return `${baseUrl}${path.replace(/^\/+/, "")}`;
}

export const roles = [
  "base",
  "proof",
  "support",
  "detail",
  "target",
  "annotation",
  "note",
  "prop",
  "accent3d",
];

export const zBands = {
  z0: "board slab",
  z1: "map/base materials",
  z2: "placements, strip, checklist, report",
  z3: "tape, labels, clip, annotations",
  z4: "optional 3d accent",
};

export const palette = {
  bg: "#0a1015",
  bg2: "#111922",
  text: "#f1eadf",
  subtext: "#b5aca0",
  red: "#b64038",
  redDark: "#8d302b",
  paper: "#ddd3c2",
  line: "rgba(255,255,255,0.08)",
};

export const curatedAssets = {
  core: {
    mapBase: assetPath("/hero-curated/core/map-base.png"),
    mapMasterRust: assetPath("/hero-curated/core/map-master-rust.png"),
    mapSupportRust: assetPath("/hero-curated/core/map-support-rust.jpg"),
    paperOverlay: assetPath("/hero-curated/core/paper-overlay.jpg"),
    vellumOverlay: assetPath("/hero-curated/core/vellum-overlay.png"),
    grainOverlay: assetPath("/hero-curated/core/grain-overlay.png"),
  },
  cards: {
    primary: assetPath("/hero-curated/cards/card-primary.webp"),
    secondary: assetPath("/hero-curated/cards/card-secondary.webp"),
    detail: assetPath("/hero-curated/cards/card-detail.png"),
    alt: assetPath("/hero-curated/cards/card-alt.jpg"),
  },
  board: {
    noteA: assetPath("/hero-curated/board/note-a.png"),
    noteB: assetPath("/hero-curated/board/note-b.png"),
    tapeA: assetPath("/hero-curated/board/tape-a.png"),
    tapeB: assetPath("/hero-curated/board/tape-b.png"),
    binderClip: assetPath("/hero-curated/board/binder-clip.png"),
    photoCornerA: assetPath("/hero-curated/board/photo-corner-a.svg"),
    photoCornerB: assetPath("/hero-curated/board/photo-corner-b.svg"),
    labelTab: assetPath("/hero-curated/board/label-tab.svg"),
    shadowMask: assetPath("/hero-curated/board/shadow-mask.png"),
    annotationCircle: assetPath("/hero-curated/board/annotation-circle.svg"),
    annotationRoute: assetPath("/hero-curated/board/annotation-route.svg"),
    annotationArrows: assetPath("/hero-curated/board/annotation-arrows.svg"),
    annotationX: assetPath("/hero-curated/board/annotation-x.svg"),
  },
};

const surfacePassContent = {
  kicker: "SURFACE PASS",
  title: "CLIENT MARKING STUDY",
  chips: ["BUILD", "SKIN", "SIGN"],
  footer: "tailored per partner brief",
};

const checklistContent = {
  heading: "run sheet",
  items: ["concept", "surface", "deploy", "capture", "report"],
};

const fileCardContent = {
  kicker: "CAMPAIGN FILE",
  title: "PROJECT: TASTEFUL",
  rows: [
    "NETWORK / selected servers",
    "SURFACES / 05 locked",
    "CAPTURE / queued",
    "REPORT / live",
  ],
};

function createLabel(id, text, x, y, width, height, rotation, className) {
  return {
    id,
    role: "prop",
    kind: "label",
    asset: curatedAssets.board.labelTab,
    alt: "",
    text,
    x,
    y,
    width,
    height,
    rotation,
    fit: "fill",
    className,
    parallaxDepth: 0.14,
  };
}

function createText(id, text, x, y, width, height, rotation, className, color) {
  return {
    id,
    role: "prop",
    kind: "text",
    text,
    x,
    y,
    width,
    height,
    rotation,
    className,
    color,
    opacity: 0.92,
    parallaxDepth: 0.1,
  };
}

const desktopLayout = {
  layers: {
    z1: [
      {
        id: "support-map-rust",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.mapSupportRust,
        alt: "Rust support map sheet",
        x: 18,
        y: 46,
        width: 580,
        height: 580,
        rotation: -7.5,
        opacity: 0.12,
        objectPosition: "50% 50%",
        className: "board-item--map board-item--map-support-a",
      },
      {
        id: "support-map-base",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.mapBase,
        alt: "Topographic support map sheet",
        x: 520,
        y: 62,
        width: 1010,
        height: 690,
        rotation: -2.4,
        opacity: 0.1,
        objectPosition: "56% 48%",
        className: "board-item--map board-item--map-support-b",
      },
      {
        id: "master-map-rust",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.mapMasterRust,
        alt: "Rust master map sheet",
        loading: "eager",
        fetchPriority: "high",
        x: 162,
        y: 126,
        width: 1084,
        height: 720,
        rotation: -2.8,
        opacity: 0.68,
        objectPosition: "50% 50%",
        className: "board-item--map board-item--map-main",
      },
      {
        id: "paper-overlay",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.paperOverlay,
        alt: "",
        x: 0,
        y: 0,
        width: 1680,
        height: 980,
        opacity: 0.07,
        blendMode: "screen",
        className: "board-item--overlay board-item--paper",
      },
      {
        id: "vellum-overlay",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.vellumOverlay,
        alt: "",
        x: 640,
        y: 186,
        width: 360,
        height: 246,
        rotation: -8.5,
        opacity: 0.09,
        fit: "fill",
        className: "board-item--vellum",
      },
      {
        id: "grain-overlay",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.grainOverlay,
        alt: "",
        x: 0,
        y: 0,
        width: 1680,
        height: 980,
        opacity: 0.11,
        blendMode: "soft-light",
        className: "board-item--overlay board-item--grain",
      },
    ],
    z2: [
      {
        id: "card-primary",
        role: "proof",
        kind: "image",
        asset: curatedAssets.cards.primary,
        alt: "Rust oilrig scene",
        loading: "eager",
        fetchPriority: "high",
        x: 1112,
        y: 90,
        width: 458,
        height: 266,
        rotation: 4.8,
        objectPosition: "52% 52%",
        className: "board-item--card board-item--card-primary",
        radius: "20px",
      },
      {
        id: "card-alt",
        role: "proof",
        kind: "image",
        asset: curatedAssets.cards.alt,
        alt: "Rust monument scene",
        x: 788,
        y: 292,
        width: 298,
        height: 176,
        rotation: 1.4,
        objectPosition: "50% 50%",
        className: "board-item--card board-item--card-alt",
        radius: "18px",
      },
      {
        id: "card-secondary",
        role: "support",
        kind: "image",
        asset: curatedAssets.cards.secondary,
        alt: "Rust swamp scene",
        x: 136,
        y: 646,
        width: 438,
        height: 248,
        rotation: -6.8,
        objectPosition: "48% 48%",
        className: "board-item--card board-item--card-secondary",
        radius: "18px",
      },
      {
        id: "card-detail",
        role: "detail",
        kind: "image",
        asset: curatedAssets.cards.detail,
        alt: "Rust map detail inset",
        loading: "eager",
        x: 734,
        y: 354,
        width: 260,
        height: 184,
        rotation: 2.8,
        className: "board-item--card board-item--detail-card",
        radius: "14px",
      },
      {
        id: "surface-pass-strip",
        role: "note",
        kind: "surfaceStrip",
        x: 270,
        y: 508,
        width: 486,
        height: 132,
        rotation: -2.6,
        className: "board-item--surface-strip",
        radius: "18px",
        content: surfacePassContent,
      },
      {
        id: "checklist-note",
        role: "note",
        kind: "checklist",
        asset: curatedAssets.board.noteB,
        alt: "",
        x: 612,
        y: 694,
        width: 218,
        height: 142,
        rotation: -0.6,
        opacity: 0.96,
        fit: "fill",
        className: "board-item--checklist",
        radius: "18px",
        content: checklistContent,
      },
      {
        id: "campaign-file-card",
        role: "note",
        kind: "fileCard",
        asset: curatedAssets.board.noteA,
        alt: "",
        x: 1086,
        y: 646,
        width: 378,
        height: 226,
        rotation: -1.2,
        opacity: 0.96,
        fit: "fill",
        className: "board-item--file-card",
        radius: "22px",
        content: fileCardContent,
      },
      {
        id: "target-zone",
        role: "target",
        kind: "target",
        x: 844,
        y: 432,
        width: 40,
        height: 40,
        className: "board-item--target",
      },
    ],
    z3: [
      {
        id: "tape-primary",
        role: "prop",
        kind: "image",
        asset: curatedAssets.board.tapeA,
        alt: "",
        x: 1178,
        y: 82,
        width: 164,
        height: 58,
        rotation: 8.2,
        className: "board-item--prop board-item--tape board-item--tape-primary",
      },
      {
        id: "tape-surface",
        role: "prop",
        kind: "image",
        asset: curatedAssets.board.tapeB,
        alt: "",
        x: 322,
        y: 492,
        width: 146,
        height: 54,
        rotation: -4.2,
        className: "board-item--prop board-item--tape board-item--tape-surface",
      },
      {
        id: "binder-clip",
        role: "prop",
        kind: "image",
        asset: curatedAssets.board.binderClip,
        alt: "",
        x: 1320,
        y: 620,
        width: 78,
        height: 78,
        rotation: 1.4,
        className: "board-item--prop board-item--clip",
      },
      {
        id: "annotation-circle",
        role: "annotation",
        kind: "annotation",
        alt: "",
        x: 760,
        y: 370,
        width: 154,
        height: 154,
        opacity: 0.62,
        className: "board-item--annotation board-item--annotation-circle",
        annotationType: "circle",
      },
      {
        id: "annotation-route",
        role: "annotation",
        kind: "annotation",
        alt: "",
        x: 804,
        y: 360,
        width: 252,
        height: 98,
        rotation: -7,
        opacity: 0.68,
        className: "board-item--annotation board-item--annotation-route",
        annotationType: "route",
      },
      {
        id: "annotation-arrows",
        role: "annotation",
        kind: "annotation",
        alt: "",
        x: 900,
        y: 312,
        width: 92,
        height: 46,
        rotation: -7.2,
        opacity: 0.72,
        className: "board-item--annotation board-item--annotation-arrows",
        annotationType: "arrows",
      },
      {
        id: "annotation-x",
        role: "annotation",
        kind: "image",
        asset: curatedAssets.board.annotationX,
        alt: "",
        x: 930,
        y: 252,
        width: 58,
        height: 34,
        rotation: -6.8,
        opacity: 0.62,
        fit: "contain",
        className: "board-item--annotation board-item--annotation-x",
      },
      createLabel(
        "placement-label-01",
        "PLACEMENT 01",
        1124,
        64,
        132,
        34,
        4.8,
        "board-item--placement-label",
      ),
      createLabel(
        "placement-label-02",
        "PLACEMENT 02",
        154,
        616,
        132,
        34,
        -6.8,
        "board-item--placement-label",
      ),
      createLabel(
        "placement-label-03",
        "PLACEMENT 03",
        806,
        258,
        128,
        32,
        1.4,
        "board-item--placement-label",
      ),
      createLabel(
        "selected-zone-label",
        "SELECTED ZONE",
        734,
        332,
        136,
        34,
        2.8,
        "board-item--placement-label board-item--detail-label",
      ),
      createText(
        "placement-note-01",
        "skyline anchor",
        1240,
        80,
        106,
        24,
        4.8,
        "board-item--handwritten board-item--handwritten-warm board-item--handwritten-compact",
        "rgba(233, 224, 210, 0.82)",
      ),
      createText(
        "placement-note-02",
        "route traffic",
        296,
        620,
        142,
        34,
        -6.8,
        "board-item--handwritten board-item--handwritten-red",
        "rgba(178, 88, 80, 0.84)",
      ),
      createText(
        "placement-note-03",
        "repeat dwell",
        944,
        248,
        92,
        24,
        1.4,
        "board-item--handwritten board-item--handwritten-warm board-item--handwritten-compact",
        "rgba(229, 219, 203, 0.78)",
      ),
    ],
  },
};

const mobileLayout = {
  layers: {
    z1: [
      {
        id: "support-map-base-mobile",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.mapBase,
        alt: "Topographic support map sheet",
        x: 74,
        y: 96,
        width: 650,
        height: 452,
        rotation: -6,
        opacity: 0.1,
        objectPosition: "56% 48%",
        className: "board-item--map board-item--map-support-b",
      },
      {
        id: "master-map-rust-mobile",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.mapMasterRust,
        alt: "Rust master map sheet",
        loading: "eager",
        fetchPriority: "high",
        x: 72,
        y: 236,
        width: 758,
        height: 758,
        rotation: -4.6,
        opacity: 0.67,
        objectPosition: "50% 50%",
        className: "board-item--map board-item--map-main",
      },
      {
        id: "support-map-rust-mobile",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.mapSupportRust,
        alt: "Rust support map sheet",
        x: 450,
        y: 126,
        width: 276,
        height: 276,
        rotation: 5.5,
        opacity: 0.1,
        objectPosition: "50% 50%",
        className: "board-item--map board-item--map-support-a",
      },
      {
        id: "paper-overlay-mobile",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.paperOverlay,
        alt: "",
        x: 0,
        y: 0,
        width: 900,
        height: 1360,
        opacity: 0.05,
        blendMode: "screen",
        className: "board-item--overlay board-item--paper",
      },
      {
        id: "vellum-overlay-mobile",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.vellumOverlay,
        alt: "",
        x: 236,
        y: 426,
        width: 254,
        height: 194,
        rotation: -8,
        opacity: 0.06,
        fit: "fill",
        className: "board-item--vellum",
      },
      {
        id: "grain-overlay-mobile",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.grainOverlay,
        alt: "",
        x: 0,
        y: 0,
        width: 900,
        height: 1360,
        opacity: 0.08,
        blendMode: "soft-light",
        className: "board-item--overlay board-item--grain",
      },
    ],
    z2: [
      {
        id: "card-primary-mobile",
        role: "proof",
        kind: "image",
        asset: curatedAssets.cards.primary,
        alt: "Rust oilrig scene",
        loading: "eager",
        fetchPriority: "high",
        x: 446,
        y: 132,
        width: 316,
        height: 188,
        rotation: 4.8,
        objectPosition: "53% 52%",
        className: "board-item--card board-item--card-primary",
        radius: "18px",
      },
      {
        id: "card-secondary-mobile",
        role: "support",
        kind: "image",
        asset: curatedAssets.cards.secondary,
        alt: "Rust swamp scene",
        x: 104,
        y: 834,
        width: 286,
        height: 168,
        rotation: -6.2,
        objectPosition: "48% 48%",
        className: "board-item--card board-item--card-secondary",
        radius: "16px",
      },
      {
        id: "card-detail-mobile",
        role: "detail",
        kind: "image",
        asset: curatedAssets.cards.detail,
        alt: "Rust map detail inset",
        loading: "eager",
        x: 418,
        y: 610,
        width: 210,
        height: 150,
        rotation: 2.8,
        className: "board-item--card board-item--detail-card",
        radius: "14px",
      },
      {
        id: "surface-pass-strip-mobile",
        role: "note",
        kind: "surfaceStrip",
        x: 118,
        y: 1038,
        width: 594,
        height: 120,
        rotation: -2.6,
        className: "board-item--surface-strip board-item--surface-strip-mobile",
        radius: "20px",
        content: surfacePassContent,
      },
      {
        id: "checklist-note-mobile",
        role: "note",
        kind: "checklist",
        asset: curatedAssets.board.noteB,
        alt: "",
        x: 146,
        y: 1188,
        width: 176,
        height: 120,
        rotation: 1.2,
        opacity: 0.96,
        fit: "fill",
        className: "board-item--checklist",
        radius: "16px",
        content: checklistContent,
      },
      {
        id: "campaign-file-card-mobile",
        role: "note",
        kind: "fileCard",
        asset: curatedAssets.board.noteA,
        alt: "",
        x: 432,
        y: 1182,
        width: 256,
        height: 154,
        rotation: -1.8,
        opacity: 0.96,
        fit: "fill",
        className: "board-item--file-card",
        radius: "18px",
        content: fileCardContent,
      },
      {
        id: "target-zone-mobile",
        role: "target",
        kind: "target",
        x: 484,
        y: 664,
        width: 34,
        height: 34,
        className: "board-item--target",
      },
    ],
    z3: [
      {
        id: "tape-primary-mobile",
        role: "prop",
        kind: "image",
        asset: curatedAssets.board.tapeA,
        alt: "",
        x: 516,
        y: 108,
        width: 138,
        height: 52,
        rotation: 7.8,
        className: "board-item--prop board-item--tape board-item--tape-primary",
      },
      {
        id: "annotation-circle-mobile",
        role: "annotation",
        kind: "annotation",
        alt: "",
        x: 406,
        y: 590,
        width: 146,
        height: 146,
        opacity: 0.74,
        className: "board-item--annotation board-item--annotation-circle",
        annotationType: "circle",
      },
      {
        id: "annotation-route-mobile",
        role: "annotation",
        kind: "annotation",
        alt: "",
        x: 516,
        y: 606,
        width: 218,
        height: 82,
        rotation: -6.4,
        opacity: 0.82,
        className: "board-item--annotation board-item--annotation-route",
        annotationType: "route",
      },
      {
        id: "annotation-arrows-mobile",
        role: "annotation",
        kind: "annotation",
        alt: "",
        x: 548,
        y: 560,
        width: 102,
        height: 48,
        rotation: -6.6,
        opacity: 0.86,
        className: "board-item--annotation board-item--annotation-arrows",
        annotationType: "arrows",
      },
      createLabel(
        "placement-label-01-mobile",
        "PLACEMENT 01",
        458,
        110,
        126,
        32,
        4.8,
        "board-item--placement-label board-item--placement-label-mobile",
      ),
      createLabel(
        "placement-label-02-mobile",
        "PLACEMENT 02",
        114,
        806,
        126,
        32,
        -6.2,
        "board-item--placement-label board-item--placement-label-mobile",
      ),
      createLabel(
        "selected-zone-label-mobile",
        "SELECTED ZONE",
        420,
        586,
        132,
        32,
        2.8,
        "board-item--placement-label board-item--detail-label board-item--placement-label-mobile",
      ),
      createText(
        "placement-note-01-mobile",
        "skyline anchor",
        564,
        122,
        88,
        24,
        4.8,
        "board-item--handwritten board-item--handwritten-warm board-item--handwritten-compact",
        "rgba(232, 223, 208, 0.78)",
      ),
      createText(
        "placement-note-02-mobile",
        "route traffic",
        242,
        812,
        104,
        28,
        -6.2,
        "board-item--handwritten board-item--handwritten-red board-item--handwritten-compact",
        "rgba(177, 90, 82, 0.82)",
      ),
    ],
  },
};

const heroManifest = {
  boardSizes,
  roles,
  zBands,
  palette,
  curatedAssets,
  layouts: {
    desktop: desktopLayout,
    mobile: mobileLayout,
  },
};

export default heroManifest;
