export const boardSizes = {
  desktop: { width: 1680, height: 980 },
  mobile: { width: 900, height: 1360 },
};

const baseUrl = import.meta.env.BASE_URL || "/";

function assetPath(path) {
  return `${baseUrl}${path.replace(/^\/+/, "")}`;
}

export const roles = [
  "base",
  "proof",
  "support",
  "detail",
  "target",
  "annotation",
  "note",
  "prop",
  "accent3d",
];

export const zBands = {
  z0: "board slab",
  z1: "map/base materials",
  z2: "placements, strip, checklist, report",
  z3: "tape, labels, clip, annotations",
  z4: "optional 3d accent",
};

export const palette = {
  bg: "#0a1015",
  bg2: "#111922",
  text: "#f1eadf",
  subtext: "#b5aca0",
  red: "#b64038",
  redDark: "#8d302b",
  paper: "#ddd3c2",
  line: "rgba(255,255,255,0.08)",
};

export const curatedAssets = {
  core: {
    mapBase: assetPath("/hero-curated/core/map-base.png"),
    mapMasterRust: assetPath("/hero-curated/core/map-master-rust.png"),
    mapSupportRust: assetPath("/hero-curated/core/map-support-rust.jpg"),
    paperOverlay: assetPath("/hero-curated/core/paper-overlay.jpg"),
    vellumOverlay: assetPath("/hero-curated/core/vellum-overlay.png"),
    grainOverlay: assetPath("/hero-curated/core/grain-overlay.png"),
  },
  cards: {
    primary: assetPath("/hero-curated/cards/card-primary.webp"),
    secondary: assetPath("/hero-curated/cards/card-secondary.webp"),
    detail: assetPath("/hero-curated/cards/card-detail.png"),
    alt: assetPath("/hero-curated/cards/card-alt.jpg"),
  },
  board: {
    noteA: assetPath("/hero-curated/board/note-a.png"),
    noteB: assetPath("/hero-curated/board/note-b.png"),
    tapeA: assetPath("/hero-curated/board/tape-a.png"),
    tapeB: assetPath("/hero-curated/board/tape-b.png"),
    binderClip: assetPath("/hero-curated/board/binder-clip.png"),
    photoCornerA: assetPath("/hero-curated/board/photo-corner-a.svg"),
    photoCornerB: assetPath("/hero-curated/board/photo-corner-b.svg"),
    labelTab: assetPath("/hero-curated/board/label-tab.svg"),
    shadowMask: assetPath("/hero-curated/board/shadow-mask.png"),
    annotationCircle: assetPath("/hero-curated/board/annotation-circle.svg"),
    annotationRoute: assetPath("/hero-curated/board/annotation-route.svg"),
    annotationArrows: assetPath("/hero-curated/board/annotation-arrows.svg"),
    annotationX: assetPath("/hero-curated/board/annotation-x.svg"),
  },
};

const surfacePassContent = {
  kicker: "SURFACE PASS",
  secondary: "CLIENT MARKING STUDY",
  chips: ["BUILD", "SKIN", "SIGN"],
};

const checklistContent = {
  heading: "run sheet",
  items: ["concept", "deploy", "capture"],
};

const fileCardContent = {
  kicker: "CAMPAIGN FILE",
  title: "PROJECT: TASTEFUL",
  rows: ["SURFACES / 05 locked", "CAPTURE / queued"],
};

function createLabel(id, text, x, y, options = {}) {
  return {
    id,
    role: "prop",
    kind: "label",
    text,
    x,
    y,
    fitContent: true,
    minWidth: options.minWidth ?? 118,
    maxWidth: options.maxWidth ?? 162,
    minHeight: options.minHeight ?? 32,
    rotation: options.rotation ?? 0,
    className: options.className,
    parallaxDepth: 0.14,
  };
}

function createAnnotationNote(id, text, x, y, options = {}) {
  return {
    id,
    role: "prop",
    kind: "annotationNote",
    text,
    x,
    y,
    fitContent: true,
    maxWidth: options.maxWidth ?? 150,
    minHeight: options.minHeight ?? 26,
    rotation: options.rotation ?? 0,
    className: options.className,
    color: options.color,
    opacity: options.opacity ?? 0.92,
    anchorSide: options.anchorSide ?? "left",
    targetId: options.targetId,
    parallaxDepth: 0.1,
  };
}

const desktopLayout = {
  layers: {
    z1: [
      {
        id: "support-map-rust",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.mapSupportRust,
        alt: "Rust support map sheet",
        x: 42,
        y: 56,
        width: 560,
        height: 520,
        rotation: -7.5,
        opacity: 0.24,
        objectPosition: "49% 48%",
        className: "board-item--map board-item--map-support-a",
        zIndex: 1,
      },
      {
        id: "support-map-base",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.mapBase,
        alt: "Topographic support map sheet",
        x: 948,
        y: 54,
        width: 504,
        height: 286,
        rotation: 4,
        opacity: 0.17,
        objectPosition: "54% 44%",
        className: "board-item--map board-item--map-support-b",
        zIndex: 2,
      },
      {
        id: "master-map-rust",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.mapMasterRust,
        alt: "Rust master map sheet",
        loading: "eager",
        fetchPriority: "high",
        x: 224,
        y: 122,
        width: 1068,
        height: 706,
        rotation: -2.4,
        opacity: 0.68,
        objectPosition: "49% 48%",
        className: "board-item--map board-item--map-main",
        zIndex: 0,
      },
      {
        id: "paper-overlay",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.paperOverlay,
        alt: "",
        x: 0,
        y: 0,
        width: 1680,
        height: 980,
        opacity: 0.07,
        blendMode: "screen",
        className: "board-item--overlay board-item--paper",
      },
      {
        id: "vellum-overlay",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.vellumOverlay,
        alt: "",
        x: 432,
        y: 196,
        width: 320,
        height: 224,
        rotation: -8.2,
        opacity: 0.07,
        fit: "fill",
        className: "board-item--vellum",
      },
      {
        id: "grain-overlay",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.grainOverlay,
        alt: "",
        x: 0,
        y: 0,
        width: 1680,
        height: 980,
        opacity: 0.11,
        blendMode: "soft-light",
        className: "board-item--overlay board-item--grain",
      },
    ],
    z2: [
      {
        id: "card-primary",
        role: "proof",
        kind: "image",
        asset: curatedAssets.cards.primary,
        alt: "Rust oilrig scene",
        loading: "eager",
        fetchPriority: "high",
        x: 1152,
        y: 92,
        width: 420,
        height: 236,
        rotation: 1.8,
        objectPosition: "52% 52%",
        className: "board-item--card board-item--card-primary",
        radius: "20px",
        zIndex: 7,
      },
      {
        id: "card-alt",
        role: "proof",
        kind: "image",
        asset: curatedAssets.cards.alt,
        alt: "Rust monument scene",
        x: 900,
        y: 248,
        width: 298,
        height: 170,
        rotation: -1.6,
        objectPosition: "49% 50%",
        className: "board-item--card board-item--card-alt",
        radius: "18px",
        zIndex: 5,
      },
      {
        id: "card-secondary",
        role: "support",
        kind: "image",
        asset: curatedAssets.cards.secondary,
        alt: "Rust swamp scene",
        x: 154,
        y: 652,
        width: 404,
        height: 220,
        rotation: -6.4,
        objectPosition: "48% 48%",
        className: "board-item--card board-item--card-secondary",
        radius: "18px",
        zIndex: 4,
      },
      {
        id: "card-detail",
        role: "detail",
        kind: "image",
        asset: curatedAssets.cards.detail,
        alt: "Rust map detail inset",
        loading: "eager",
        x: 760,
        y: 354,
        width: 228,
        height: 176,
        rotation: 1,
        objectPosition: "51% 50%",
        className: "board-item--card board-item--detail-card",
        radius: "14px",
        zIndex: 6,
      },
      {
        id: "surface-pass-strip",
        role: "note",
        kind: "surfaceStrip",
        x: 314,
        y: 516,
        width: 474,
        height: 126,
        rotation: -3.6,
        className: "board-item--surface-strip",
        radius: "18px",
        content: surfacePassContent,
        zIndex: 5,
      },
      {
        id: "checklist-note",
        role: "note",
        kind: "checklist",
        asset: curatedAssets.board.noteB,
        alt: "",
        x: 672,
        y: 678,
        width: 196,
        height: 116,
        rotation: -1.2,
        opacity: 0.96,
        fit: "fill",
        className: "board-item--checklist",
        radius: "18px",
        content: checklistContent,
        zIndex: 4,
      },
      {
        id: "campaign-file-card",
        role: "note",
        kind: "fileCard",
        asset: curatedAssets.board.noteA,
        alt: "",
        x: 1108,
        y: 644,
        width: 346,
        height: 196,
        rotation: -1.8,
        opacity: 0.96,
        fit: "fill",
        className: "board-item--file-card",
        radius: "22px",
        content: fileCardContent,
        zIndex: 5,
      },
      {
        id: "target-zone",
        role: "target",
        kind: "target",
        x: 892,
        y: 468,
        width: 44,
        height: 44,
        className: "board-item--target",
        zIndex: 8,
      },
    ],
    z3: [
      {
        id: "tape-primary",
        role: "prop",
        kind: "image",
        asset: curatedAssets.board.tapeA,
        alt: "",
        x: 1256,
        y: 80,
        width: 154,
        height: 54,
        rotation: 4.8,
        className: "board-item--prop board-item--tape board-item--tape-primary",
      },
      {
        id: "tape-surface",
        role: "prop",
        kind: "image",
        asset: curatedAssets.board.tapeB,
        alt: "",
        x: 386,
        y: 502,
        width: 150,
        height: 54,
        rotation: -6,
        className: "board-item--prop board-item--tape board-item--tape-surface",
      },
      {
        id: "binder-clip",
        role: "prop",
        kind: "image",
        asset: curatedAssets.board.binderClip,
        alt: "",
        x: 1246,
        y: 618,
        width: 82,
        height: 82,
        rotation: 1.8,
        className: "board-item--prop board-item--clip",
      },
      {
        id: "annotation-route-major",
        role: "annotation",
        kind: "annotation",
        alt: "",
        x: 330,
        y: 156,
        width: 1136,
        height: 632,
        rotation: -3.4,
        opacity: 0.84,
        className: "board-item--annotation board-item--annotation-route-major",
        annotationType: "flowRoute",
        zIndex: 1,
      },
      {
        id: "annotation-circle-site",
        role: "annotation",
        kind: "annotation",
        alt: "",
        x: 822,
        y: 388,
        width: 186,
        height: 176,
        rotation: -7,
        opacity: 0.9,
        className:
          "board-item--annotation board-item--annotation-circle-primary",
        annotationType: "circle",
        zIndex: 2,
      },
      {
        id: "annotation-circle-hero",
        role: "annotation",
        kind: "annotation",
        alt: "",
        x: 1248,
        y: 132,
        width: 190,
        height: 118,
        rotation: 7.8,
        opacity: 0.82,
        className:
          "board-item--annotation board-item--annotation-circle-focus board-item--annotation-circle-hero",
        annotationType: "circle",
        zIndex: 3,
      },
      {
        id: "annotation-circle-mid",
        role: "annotation",
        kind: "annotation",
        alt: "",
        x: 988,
        y: 282,
        width: 126,
        height: 82,
        rotation: -9,
        opacity: 0.8,
        className:
          "board-item--annotation board-item--annotation-circle-focus board-item--annotation-circle-mid",
        annotationType: "circle",
        zIndex: 3,
      },
      {
        id: "annotation-circle-lower",
        role: "annotation",
        kind: "annotation",
        alt: "",
        x: 274,
        y: 698,
        width: 162,
        height: 98,
        rotation: -10.5,
        opacity: 0.82,
        className:
          "board-item--annotation board-item--annotation-circle-focus board-item--annotation-circle-lower",
        annotationType: "circle",
        zIndex: 3,
      },
      {
        id: "annotation-arrow-zone",
        role: "annotation",
        kind: "annotation",
        alt: "",
        x: 962,
        y: 362,
        width: 126,
        height: 96,
        rotation: 2,
        opacity: 0.82,
        className:
          "board-item--annotation board-item--annotation-arrow board-item--annotation-arrow-zone",
        annotationType: "arrow",
        annotationVariant: "drop",
        zIndex: 4,
      },
      {
        id: "annotation-arrow-hero",
        role: "annotation",
        kind: "annotation",
        alt: "",
        x: 1086,
        y: 170,
        width: 188,
        height: 110,
        rotation: -5,
        opacity: 0.8,
        className:
          "board-item--annotation board-item--annotation-arrow board-item--annotation-arrow-hero",
        annotationType: "arrow",
        zIndex: 4,
      },
      createLabel(
        "placement-label-01",
        "PLACEMENT 01",
        1170,
        64,
        {
          minWidth: 122,
          maxWidth: 154,
          minHeight: 32,
          rotation: 1.8,
          className: "board-item--placement-label",
        },
      ),
      createLabel(
        "placement-label-02",
        "PLACEMENT 02",
        920,
        216,
        {
          minWidth: 122,
          maxWidth: 154,
          minHeight: 32,
          rotation: -1.6,
          className: "board-item--placement-label",
        },
      ),
      createLabel(
        "placement-label-03",
        "PLACEMENT 03",
        170,
        626,
        {
          minWidth: 120,
          maxWidth: 150,
          minHeight: 30,
          rotation: -6.4,
          className: "board-item--placement-label",
        },
      ),
      createLabel(
        "selected-zone-label",
        "SELECTED ZONE",
        742,
        330,
        {
          minWidth: 126,
          maxWidth: 162,
          minHeight: 32,
          rotation: 1,
          className: "board-item--placement-label board-item--detail-label",
        },
      ),
      createAnnotationNote(
        "placement-note-01",
        "skyline anchor",
        1410,
        132,
        {
          maxWidth: 128,
          rotation: 1.8,
          anchorSide: "left",
          targetId: "card-primary",
          className:
            "board-item--annotation-note board-item--handwritten board-item--handwritten-warm board-item--handwritten-compact",
          color: "rgba(233, 224, 210, 0.82)",
        },
      ),
      createAnnotationNote(
        "placement-note-02",
        "repeat dwell",
        868,
        276,
        {
          maxWidth: 108,
          rotation: -1.6,
          anchorSide: "right",
          targetId: "card-alt",
          className:
            "board-item--annotation-note board-item--handwritten board-item--handwritten-warm board-item--handwritten-compact",
          color: "rgba(229, 219, 203, 0.8)",
        },
      ),
      createAnnotationNote(
        "placement-note-03",
        "route traffic",
        504,
        736,
        {
          maxWidth: 122,
          rotation: -4.8,
          anchorSide: "left",
          targetId: "card-secondary",
          className:
            "board-item--annotation-note board-item--handwritten board-item--handwritten-red",
          color: "rgba(178, 88, 80, 0.84)",
        },
      ),
      createAnnotationNote(
        "placement-note-04",
        "primary site",
        1000,
        492,
        {
          maxWidth: 100,
          rotation: 0.6,
          anchorSide: "left",
          targetId: "target-zone",
          className:
            "board-item--annotation-note board-item--handwritten board-item--handwritten-red board-item--handwritten-compact",
          color: "rgba(178, 88, 80, 0.84)",
        },
      ),
    ],
  },
};

const mobileLayout = {
  layers: {
    z1: [
      {
        id: "support-map-base-mobile",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.mapBase,
        alt: "Topographic support map sheet",
        x: 40,
        y: 112,
        width: 604,
        height: 360,
        rotation: -7.2,
        opacity: 0.11,
        objectPosition: "55% 48%",
        className: "board-item--map board-item--map-support-b",
        zIndex: 2,
      },
      {
        id: "support-map-rust-mobile",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.mapSupportRust,
        alt: "Rust support map sheet",
        x: 548,
        y: 118,
        width: 220,
        height: 214,
        rotation: 6.4,
        opacity: 0.08,
        objectPosition: "50% 50%",
        className: "board-item--map board-item--map-support-a",
        zIndex: 1,
      },
      {
        id: "master-map-rust-mobile",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.mapMasterRust,
        alt: "Rust master map sheet",
        loading: "eager",
        fetchPriority: "high",
        x: 92,
        y: 228,
        width: 722,
        height: 688,
        rotation: -3.8,
        opacity: 0.72,
        objectPosition: "50% 50%",
        className: "board-item--map board-item--map-main",
        zIndex: 0,
      },
      {
        id: "paper-overlay-mobile",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.paperOverlay,
        alt: "",
        x: 0,
        y: 0,
        width: 900,
        height: 1360,
        opacity: 0.05,
        blendMode: "screen",
        className: "board-item--overlay board-item--paper",
      },
      {
        id: "vellum-overlay-mobile",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.vellumOverlay,
        alt: "",
        x: 260,
        y: 420,
        width: 196,
        height: 148,
        rotation: -6.8,
        opacity: 0.04,
        fit: "fill",
        className: "board-item--vellum",
      },
      {
        id: "grain-overlay-mobile",
        role: "base",
        kind: "image",
        asset: curatedAssets.core.grainOverlay,
        alt: "",
        x: 0,
        y: 0,
        width: 900,
        height: 1360,
        opacity: 0.08,
        blendMode: "soft-light",
        className: "board-item--overlay board-item--grain",
      },
    ],
    z2: [
      {
        id: "card-primary-mobile",
        role: "proof",
        kind: "image",
        asset: curatedAssets.cards.primary,
        alt: "Rust oilrig scene",
        loading: "eager",
        fetchPriority: "high",
        x: 476,
        y: 96,
        width: 330,
        height: 194,
        rotation: 3.8,
        objectPosition: "53% 52%",
        className: "board-item--card board-item--card-primary",
        radius: "18px",
        zIndex: 7,
      },
      {
        id: "card-secondary-mobile",
        role: "support",
        kind: "image",
        asset: curatedAssets.cards.secondary,
        alt: "Rust swamp scene",
        x: 104,
        y: 770,
        width: 292,
        height: 172,
        rotation: -5.6,
        objectPosition: "48% 48%",
        className: "board-item--card board-item--card-secondary",
        radius: "16px",
        zIndex: 4,
      },
      {
        id: "card-detail-mobile",
        role: "detail",
        kind: "image",
        asset: curatedAssets.cards.detail,
        alt: "Rust map detail inset",
        loading: "eager",
        x: 386,
        y: 500,
        width: 236,
        height: 176,
        rotation: 1.2,
        objectPosition: "51% 50%",
        className: "board-item--card board-item--detail-card",
        radius: "14px",
        zIndex: 6,
      },
      {
        id: "surface-pass-strip-mobile",
        role: "note",
        kind: "surfaceStrip",
        x: 96,
        y: 1018,
        width: 472,
        height: 118,
        rotation: -2.4,
        className: "board-item--surface-strip board-item--surface-strip-mobile",
        radius: "20px",
        content: surfacePassContent,
        zIndex: 5,
      },
      {
        id: "campaign-file-card-mobile",
        role: "note",
        kind: "fileCard",
        asset: curatedAssets.board.noteA,
        alt: "",
        x: 450,
        y: 1116,
        width: 286,
        height: 178,
        rotation: -1.6,
        opacity: 0.96,
        fit: "fill",
        className: "board-item--file-card",
        radius: "18px",
        content: fileCardContent,
        zIndex: 5,
      },
      {
        id: "target-zone-mobile",
        role: "target",
        kind: "target",
        x: 470,
        y: 612,
        width: 40,
        height: 40,
        className: "board-item--target",
        zIndex: 8,
      },
    ],
    z3: [
      {
        id: "tape-primary-mobile",
        role: "prop",
        kind: "image",
        asset: curatedAssets.board.tapeA,
        alt: "",
        x: 564,
        y: 78,
        width: 142,
        height: 52,
        rotation: 6.8,
        className: "board-item--prop board-item--tape board-item--tape-primary",
      },
      {
        id: "annotation-route-major-mobile",
        role: "annotation",
        kind: "annotation",
        alt: "",
        x: 176,
        y: 174,
        width: 534,
        height: 714,
        rotation: -4.4,
        opacity: 0.78,
        className: "board-item--annotation board-item--annotation-route-major",
        annotationType: "flowRoute",
        zIndex: 1,
      },
      {
        id: "annotation-circle-site-mobile",
        role: "annotation",
        kind: "annotation",
        alt: "",
        x: 402,
        y: 550,
        width: 166,
        height: 156,
        rotation: -7.2,
        opacity: 0.88,
        className:
          "board-item--annotation board-item--annotation-circle-primary",
        annotationType: "circle",
        zIndex: 2,
      },
      {
        id: "annotation-circle-hero-mobile",
        role: "annotation",
        kind: "annotation",
        alt: "",
        x: 564,
        y: 142,
        width: 150,
        height: 94,
        rotation: 6.4,
        opacity: 0.8,
        className:
          "board-item--annotation board-item--annotation-circle-focus board-item--annotation-circle-hero",
        annotationType: "circle",
        zIndex: 3,
      },
      {
        id: "annotation-circle-lower-mobile",
        role: "annotation",
        kind: "annotation",
        alt: "",
        x: 188,
        y: 806,
        width: 150,
        height: 94,
        rotation: -10.4,
        opacity: 0.8,
        className:
          "board-item--annotation board-item--annotation-circle-focus board-item--annotation-circle-lower",
        annotationType: "circle",
        zIndex: 3,
      },
      {
        id: "annotation-arrow-zone-mobile",
        role: "annotation",
        kind: "annotation",
        alt: "",
        x: 520,
        y: 520,
        width: 142,
        height: 92,
        rotation: -10,
        opacity: 0.78,
        className:
          "board-item--annotation board-item--annotation-arrow board-item--annotation-arrow-zone",
        annotationType: "arrow",
        zIndex: 4,
      },
      createLabel(
        "placement-label-01-mobile",
        "PLACEMENT 01",
        492,
        64,
        {
          minWidth: 116,
          maxWidth: 148,
          minHeight: 30,
          rotation: 3.8,
          className: "board-item--placement-label board-item--placement-label-mobile",
        },
      ),
      createLabel(
        "placement-label-03-mobile",
        "PLACEMENT 03",
        118,
        744,
        {
          minWidth: 114,
          maxWidth: 144,
          minHeight: 28,
          rotation: -5.6,
          className: "board-item--placement-label board-item--placement-label-mobile",
        },
      ),
      createLabel(
        "selected-zone-label-mobile",
        "SELECTED ZONE",
        372,
        470,
        {
          minWidth: 122,
          maxWidth: 152,
          minHeight: 30,
          rotation: 1.2,
          className:
            "board-item--placement-label board-item--detail-label board-item--placement-label-mobile",
        },
      ),
      createAnnotationNote(
        "placement-note-01-mobile",
        "skyline anchor",
        702,
        130,
        {
          maxWidth: 112,
          rotation: 3.8,
          anchorSide: "left",
          targetId: "card-primary-mobile",
          className:
            "board-item--annotation-note board-item--handwritten board-item--handwritten-warm board-item--handwritten-compact",
          color: "rgba(232, 223, 208, 0.8)",
        },
      ),
      createAnnotationNote(
        "placement-note-03-mobile",
        "route traffic",
        378,
        888,
        {
          maxWidth: 116,
          rotation: -4.6,
          anchorSide: "left",
          targetId: "card-secondary-mobile",
          className:
            "board-item--annotation-note board-item--handwritten board-item--handwritten-red board-item--handwritten-compact",
          color: "rgba(177, 90, 82, 0.84)",
        },
      ),
      createAnnotationNote(
        "placement-note-04-mobile",
        "primary site",
        532,
        626,
        {
          maxWidth: 92,
          rotation: 0.8,
          anchorSide: "left",
          targetId: "target-zone-mobile",
          className:
            "board-item--annotation-note board-item--handwritten board-item--handwritten-red board-item--handwritten-compact",
          color: "rgba(177, 90, 82, 0.84)",
        },
      ),
    ],
  },
};

const heroManifest = {
  boardSizes,
  roles,
  zBands,
  palette,
  curatedAssets,
  layouts: {
    desktop: desktopLayout,
    mobile: mobileLayout,
  },
};

export default heroManifest;
